[project]
name = "project-log"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.2",
    "pytest>=9.0.3",
    "pyyaml>=6.0.3",
    "scrummd>=0.2.0",
    "watchdog>=6.0.0",
]

[tool.scrummd]
scrum_path = "scrum"
strict = true
allow_header_summary = true

[tool.scrummd.collections.backlog]
required = ["status", "points", "priority", "role"]

[tool.scrummd.collections.backlog.fields]
status = ["Backlog", "To Do", "In Progress", "Done", "Blocked", "Dropped"]
priority = ["Low", "Medium", "High", "Critical"]
points = [0, 1, 2, 3, 5, 8, 13, 21]
role = ["Scrum Master", "Developer", "Researcher", "Tester", "Stakeholder"]

[tool.scrummd.collections.sprints]
required = ["status", "points", "sprint", "role"]

[tool.scrummd.collections.sprints.fields]
status = ["To Do", "In Progress", "Done", "Blocked"]
sprint = "integer"

[tool.scrummd.collections.dropped]
required = ["status", "points", "priority", "role"]

[tool.scrummd.collections.dropped.fields]
status = ["Dropped"]
priority = ["Low", "Medium", "High", "Critical"]
points = [0, 1, 2, 3, 5, 8, 13, 21]
role = ["Scrum Master", "Developer", "Researcher", "Tester", "Stakeholder"]

# Configuration for 'sbl' (Scrum Backlog)
[tool.scrummd.sbl]
columns = ["index", "summary", "status", "points", "priority"]

# Configuration for 'sboard' (Scrum Board)
[tool.scrummd.sboard]
columns = ["To Do", "In Progress", "Done"]
default_group_by = "status"

# Configuration for 'scard' (Scrum Card)
[tool.scrummd.scard]
default_template = "default"
